# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pwd', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
