# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170722_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
