# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='\u59d3')),
                ('last_name', models.CharField(max_length=40, verbose_name='\u540d')),
                ('age', models.IntegerField(default=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['first_name'],
                'verbose_name': '\u4f5c\u8005',
                'verbose_name_plural': '\u4f5c\u8005',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u4e66\u540d')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='myapp.Author')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u56fe\u4e66',
                'verbose_name_plural': '\u56fe\u4e66',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
                ('address', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('city', models.CharField(max_length=60, verbose_name='\u57ce\u5e02')),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50, verbose_name='\u56fd\u5bb6')),
                ('Website', models.URLField(null=True, verbose_name='\u7f51\u5740')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'publisher',
                'verbose_name': '\u51fa\u7248\u793e',
                'verbose_name_plural': '\u51fa\u7248\u793e',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Publisher'),
        ),
    ]
