# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170720_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(default=1, verbose_name='\u7f51\u5740'),
            preserve_default=False,
        ),
    ]
