# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170802_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publish',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 3, 10, 59, 32, 608618), verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
