# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170724_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
