# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170724_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='showtime',
            field=models.DateTimeField(null=True),
        ),
    ]
